---
- name: Update apt's package index
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family | lower == "debian"

- name: Install WeeChat
  ansible.builtin.apt:
    name:
      - weechat
    state: present
  become: true
  when: ansible_os_family | lower == "debian"

- name: Create WeeChat's certificates directory
  ansible.builtin.file:
    path: "{{ _weechat_certs_directory }}"
    owner: "{{ weechat_user }}"
    group: "{{ weechat_user }}"
    state: directory
    mode: "775"
  become: true

- name: Add the WeeChat certificates
  ansible.builtin.copy:
    dest: "{{ _weechat_certs_directory }}/{{ item | basename }}"
    src: "{{ item }}"
    owner: "{{ weechat_user }}"
    group: "{{ weechat_user }}"
    mode: "600"
  become: true
  loop: "{{ weechat_tls_cert_controller_paths }}"
