---
- name: Grab a LXD release tarball, and extract the archive
  ansible.builtin.unarchive:
    src: https://github.com/lxc/lxd/releases/download/lxd-{{ lxd_release_version }}/{{ _lxd_extracted_dir }}.tar.gz
    dest: "{{ lxd_extracted_tarball_path }}"
    remote_src: yes
  become: yes

- name: Build the LXD libraries
  ansible.builtin.shell:
    chdir: "{{ lxd_extracted_tarball_path }}/{{ _lxd_extracted_dir }}"
    cmd: make deps
  become: yes

- name: Build LXD
  ansible.builtin.shell:
    chdir: "{{ lxd_extracted_tarball_path }}/{{ _lxd_extracted_dir }}"
    cmd: make
  become: yes
  environment:
    - CGO_CFLAGS: "{{ _lxd_cgo_cflags }}"
    - CGO_LDFLAGS: "{{ _lxd_cgo_ldflags }}"
    - CGO_LDFLAGS_ALLOW: "{{ _lxd_cgo_ldflags_allow }}"
    - LD_LIBRARY_PATH: "{{ _lxd_ld_library_path }}"
    - GOPATH: "{{ lxd_go_path }}"
