---
- name: Add systemd network files
  ansible.builtin.template:
    src: systemd.network.j2
    dest: /etc/systemd/network/{{ item.filename }}
    owner: root
    group: root
    mode: "644"
    force: false
  become: true
  notify:
    - Start and enable systemd-networkd
    - Remove the 'networking' daemon interfaces file (debian-like)
    - Stop and disable the 'networking' daemon (debian-like)
    - Restart systemd-networkd
  loop: "{{ systemd_networkd_files }}"
