---
- name: Update apt's package index (debian-like)
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family | lower == "debian"

- name: Install packages required to run the reload-udev-offline script (debian-like)
  ansible.builtin.apt:
    name:
      - jq
    state: present
  become: true
  when: ansible_os_family | lower == "debian"

- name: Create the administrator managed libexec directory
  ansible.builtin.file:
    path: /usr/local/libexec/systemd
    state: directory
    mode: "775"
  become: true
  register: systemd_networkd_admin_managed_libexec_dir

- name: Create the reload-udev-offline script
  ansible.builtin.template:
    src: reload-udev-offline.j2
    dest: "{{ systemd_networkd_admin_managed_libexec_dir.path }}/reload-udev-offline"
    mode: "744"
  become: true
  register: systemd_networkd_reload_udev_offline_script

- name: Create a reload-udev-offline service unit file
  ansible.builtin.template:
    src: reload-udev-offline.service.j2
    dest: /etc/systemd/system/reload-udev-offline.service
    mode: "644"
  become: true

- name: Create a reload-udev-offline timer unit file
  ansible.builtin.template:
    src: reload-udev-offline.timer.j2
    dest: /etc/systemd/system/reload-udev-offline.timer
    mode: "644"
  become: true

- name: Add the systemd-networkd service files
  ansible.builtin.template:
    src: systemd.syntax.j2
    dest: /etc/systemd/network/{{ item.filename }}
    trim_blocks: true
    lstrip_blocks: true
    owner: root
    group: root
    mode: "644"
    force: false
  become: true
  notify:
    - Enable and start the systemd-networkd service
    - Remove the networking service's interfaces file (debian-like)
    - Stop and disable the networking service (debian-like)
    - Restart the systemd-networkd service
    - Reload udev while offline
  loop: "{{ systemd_networkd_files }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
