---
- name: Update apt's package index
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family | lower == "debian"

- name: Install Helm dependencies (debian-like)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
  become: true
  when: ansible_os_family | lower == "debian"

- name: Create the {{ ansible_user_id }}'s "Downloads" directory
  ansible.builtin.file:
    path: "{{ _helm_download_dir }}"
    state: directory
    mode: "700"

- name: Grab Helm's official GPG key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: "{{ _helm_keyring_download_path }}"
    mode: "644"
  notify:
    - Remove Helm's installed GPG key
    - Install Helm's GPG key

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add Helm's apt repository (x86_64)
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by={{ _helm_keyring_install_path }}]
      https://baltocdn.com/helm/stable/debian/ all main
    state: present
  become: true
  when:
    - ansible_os_family | lower == "debian"
    - ansible_architecture == "x86_64"

- name: Install Helm (debian-like)
  ansible.builtin.apt:
    name:
      - helm
    state: present
  become: true
  when: ansible_os_family | lower == "debian"
