---
- name: Update Container Servers
  hosts: ctrservers

  tasks:
    - name: Create base Downloads directory
      ansible.builtin.file:
        path: "{{ ansible_env['HOME'] }}/Downloads"
        state: directory
        mode: "700"

    - name: Install python dependencies
      ansible.builtin.apt:
        pkg:
        - python3-venv
        state: present
        update_cache: yes
      become: yes

    - name: Create python-virtual environments directory
      ansible.builtin.file:
        path: "{{ ansible_python_virtualenvs_path }}"
        state: directory
        mode: "755"

    - name: Check if sourcing virtualenv already in .bashrc
      lineinfile:
        state: absent
        path: "{{ ansible_env['HOME'] }}/.bashrc"
        regexp: '^source "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}/bin/activate"'
      check_mode: true
      changed_when: false
      register: sourcing_virtualenv_check

    # one-liner inspired by (question not the answer, the line parameter):
    # https://stackoverflow.com/questions/53951409/line-break-with-lineinfile-in-ansible
    - name: Append .bashrc with command to activate ansible virtualenv
      ansible.builtin.lineinfile:
        path: "{{ ansible_env['HOME'] }}/.bashrc"
        regexp: '^source "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}/bin/activate"'
        line: "\n# ANSIBLE MANAGED\nsource \"{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}/bin/activate\""
      when: sourcing_virtualenv_check.found == 0

    - name: Install base python packages
      ansible.builtin.pip:
        name: netaddr
        virtualenv: "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}"
        virtualenv_command: /usr/bin/python3 -m venv "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}"

    - name: Install Docker dependencies
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - curl
        state: present
        update_cache: yes
      become: yes

    - name: Install debootstrap dependencies
      ansible.builtin.apt:
        pkg:
        - debootstrap
        - debian-archive-keyring
        state: present
        update_cache: yes
      become: yes

    - name: Install systemd-container dependencies
      ansible.builtin.apt:
        pkg:
        - systemd-container
        - bridge-utils
        state: present
        update_cache: yes
      become: yes

    - name: Grab Docker's Official GPG key
      ansible.builtin.uri:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        method: GET
        follow_redirects: safe
        dest: "{{ docker_keyring_download_path }}"
        # 304 redirect is ok
        status_code: [200, 304]
      notify:
        - Remove Docker's Installed GPG key, If Exists
        - Install Docker's GPG key

    - name: Flush handlers
      meta: flush_handlers

    - name: Add Docker's stable apt repository (x86_64)
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by={{ docker_keyring_install_path }}]
          https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      become: yes
      when: ansible_architecture == "x86_64"

    - name: Install the Docker Engine
      ansible.builtin.apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: present
        update_cache: yes
      become: yes

  handlers:
    - name: Remove Docker's Installed GPG key, If Exists
      ansible.builtin.file:
        path: "{{ docker_keyring_install_path }}"
        state: absent
      become: yes

    # --batch option is needed for gpg due to odd "gpg: cannot open '/dev/tty'" error.
    # For reference:
    # https://github.com/pipech/erpnext-docker-debian/issues/26
    - name: Install Docker's GPG key
      ansible.builtin.shell: |
        gpg --batch --output {{ docker_keyring_install_path }} --dearmor {{ docker_keyring_download_path }}
      become: yes

- name: Setup systemd-networkd networking
  hosts: ctrservers
  become: true

  tasks:
    - name: Add systemd network files
      ansible.builtin.template:
        src: systemd.network.j2
        dest: /etc/systemd/network/{{ ansible_hostname }}-{{ item.filename }}
        owner: root
        group: root
        mode: "644"
        force: no
      vars:
        subnet_prefix: "{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ansible.netcommon.ipaddr('prefix') }}"
        bridge_interface: "br0"
      loop:
        # Everything under 'filename' will be recorded in the systemd network files template.
        # Each section header is determined by the top level key in each hash.
        - filename: "{{ ansible_default_ipv4.interface }}.link"
          Match:
            MACAddress: "{{ ansible_default_ipv4.macaddress }}"
          Link:
            NamePolicy: keep

        - filename: "{{ ansible_default_ipv4.interface }}.network"
          Match:
            Name: "{{ ansible_default_ipv4.interface }}"
          Network:
            Bridge: "{{ bridge_interface }}"

        - filename: "{{ bridge_interface }}.netdev"
          NetDev:
            Name: "{{ bridge_interface }}"
            Kind: bridge
            MACAddress: "{{ '00:00:00' | community.general.random_mac }}"

        - filename: "{{ bridge_interface }}.network"
          Match:
            Name: "{{ bridge_interface }}"
          Network:
            DNS: "{{ ansible_default_ipv4.gateway }}"
            Address: "{{ (ansible_default_ipv4.address + '/' + subnet_prefix) }}"
            Gateway: "{{ ansible_default_ipv4.gateway }}"
      notify:
        - Start and enable systemd-networkd
        - Remove Debian's networking daemon interfaces file
        - Stop and disable Debian networking daemon
        - Restart systemd-networkd
      when: ansible_default_ipv4.interface != bridge_interface

  handlers:
    - name: Start and enable systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Remove Debian's networking daemon interfaces file
      ansible.builtin.file:
        path: /etc/network/interfaces
        state: absent
      when: ansible_distribution == "Debian"

    - name: Stop and disable Debian networking daemon
      ansible.builtin.systemd:
        name: networking
        enabled: no
        state: stopped
      when: ansible_distribution == "Debian"

    - name: Restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        enabled: yes
        state: restarted

# - name: Create Container Nodes
#   hosts: ctrservers

#   tasks:
#     # DISCUSS(cavcrosby): this task sets if the rest of the task list should run.
#     # However, handlers doesn't quite work here because multiple changes could
#     # have occurred and I don't wise to delegate how to determine what changed to the
#     # handlers. That said, this could be refactored due to looping is needed now
#     # for each task.
#     - name: Create systemd container bases
#       ansible.builtin.file:
#         path: /var/lib/machines/{{ hostvars[item]['inventory_hostname'] }}
#         state: directory
#         mode: "755"
#       become: yes
#       register: create_systemd_containers_bases
#       loop: "{{ groups['containers'] }}"

#     - name: Generate systemd container contents
#       ansible.builtin.command: |
#         debootstrap --include=systemd-container,sudo bullseye {{ item.path }}
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Start newly created systemd containers
#       ansible.builtin.command: |
#         machinectl start {{ item.item }}
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     # TODO(cavcrosby): this could be refactored due to each command needing the same
#     # boilerplate, but running everything in a shell module with a literal block
#     # scalar appeared to not work.
#     #
#     # inspired by:
#     # https://bbs.archlinux.org/viewtopic.php?id=237096
#     - name: Add ansible group
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "groupadd ansible"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Add ansible user
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "useradd --gid ansible --shell /bin/bash --create-home --home-dir /home/ansible ansible"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Configure ansible password
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "echo ansible:Passw0rd! | chpasswd"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Add ansible to sudoers
#       ansible.builtin.shell: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "echo 'ansible  ALL=(ALL:ALL) ALL' > /etc/sudoers.d/ansible"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Lock root account
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "passwd --lock --delete root"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

    # - name: Debug
    #   ansible.builtin.debug:
    #     var: hostvars[item]['type']
    #   loop: "{{ groups['containers'] }}"

# - name: Configure Container Nodes
#   hosts: altaria_containers
  
#   roles:
#     - altaria

#
# DISCUSS(cavcrosby): implement this play, essentially here is where each systemd
# container will be created and along with its appropriate .nspawn file.
