---
- name: Update Container Servers
  hosts: ctrservers

  roles:
    - lxd-source

  tasks:
    - name: Create {{ ansible_user_id }}'s Downloads directory
      ansible.builtin.file:
        path: "{{ ansible_env['HOME'] }}/Downloads"
        state: directory
        mode: "700"

    - name: Install python dependencies
      ansible.builtin.apt:
        pkg:
        - python3-venv
        state: present
        update_cache: yes
      become: yes

    - name: Create python-virtual environments directory
      ansible.builtin.file:
        path: "{{ ansible_python_virtualenvs_path }}"
        state: directory
        mode: "755"

    - name: Add sourcing the {{ ansible_python_virtualenv }} python virtualenv
      ansible.builtin.import_role:
        name: common
        tasks_from: lbyl_lineinfile
      vars:
        path: "{{ ansible_env['HOME'] }}/.bashrc"
        regexp: '^source "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}/bin/activate"'
        line: "source \"{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}/bin/activate\""
        line_identifier: "sourcing the {{ ansible_python_virtualenv }} python virtualenv"

    - name: Install base python packages
      ansible.builtin.pip:
        name: netaddr
        virtualenv: "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}"
        virtualenv_command: /usr/bin/python3 -m venv "{{ ansible_python_virtualenvs_path }}/{{ ansible_python_virtualenv }}"

    - name: Install Docker dependencies
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - curl
        state: present
        update_cache: yes
      become: yes

    - name: Grab Docker's Official GPG key
      ansible.builtin.uri:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        method: GET
        follow_redirects: safe
        dest: "{{ docker_keyring_download_path }}"
        # 304 redirect is ok
        status_code: [200, 304]
      notify:
        - Remove Docker's Installed GPG key, If Exists
        - Install Docker's GPG key

    - name: Flush handlers
      meta: flush_handlers

    - name: Add Docker's stable apt repository (x86_64)
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by={{ docker_keyring_install_path }}]
          https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      become: yes
      when: ansible_architecture == "x86_64"

    - name: Install the Docker Engine
      ansible.builtin.apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: present
        update_cache: yes
      become: yes

  handlers:
    - name: Remove Docker's Installed GPG key, If Exists
      ansible.builtin.file:
        path: "{{ docker_keyring_install_path }}"
        state: absent
      become: yes

    # --batch option is needed for gpg due to odd "gpg: cannot open '/dev/tty'" error.
    # For reference:
    # https://github.com/pipech/erpnext-docker-debian/issues/26
    - name: Install Docker's GPG key
      ansible.builtin.shell: |
        gpg --batch --output {{ docker_keyring_install_path }} --dearmor {{ docker_keyring_download_path }}
      become: yes

- name: Setup systemd-networkd networking
  hosts: ctrservers
  become: true

  tasks:
    - name: Add systemd network files
      ansible.builtin.template:
        src: systemd.network.j2
        dest: /etc/systemd/network/{{ ansible_hostname }}-{{ item.filename }}
        owner: root
        group: root
        mode: "644"
        force: no
      loop:
        # Everything under 'filename' will be recorded in the systemd network files template.
        # Each section header is determined by the top level key in each hash.
        - filename: "{{ ansible_default_ipv4.interface }}.link"
          Match:
            MACAddress: "{{ ansible_default_ipv4.macaddress }}"
          Link:
            NamePolicy: keep

        - filename: "{{ ansible_default_ipv4.interface }}.network"
          Match:
            Name: "{{ ansible_default_ipv4.interface }}"
          Network:
            DHCP: "ipv4"
      vars:
        subnet_prefix: "{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ansible.netcommon.ipaddr('prefix') }}"
      notify:
        - Start and enable systemd-networkd
        - Remove Debian's networking daemon interfaces file
        - Stop and disable Debian networking daemon
        - Restart systemd-networkd

  handlers:
    - name: Start and enable systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Remove Debian's networking daemon interfaces file
      ansible.builtin.file:
        path: /etc/network/interfaces
        state: absent
      when: ansible_distribution == "Debian"

    - name: Stop and disable Debian networking daemon
      ansible.builtin.systemd:
        name: networking
        enabled: no
        state: stopped
      when: ansible_distribution == "Debian"

    - name: Restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        enabled: yes
        state: restarted

- name: Create Container Nodes
  hosts: localhost
  connection: local

  tasks:
    # - name: Debug
    #   ansible.builtin.debug:
    #     var: hostvars[item]['type']
    #   loop: "{{ groups['containers'] }}"

    # DISCUSS(cavcrosby): this task sets if the rest of the task list should run.
    # However, handlers doesn't quite work here because multiple changes could
    # have occurred and I don't wise to delegate how to determine what changed to the
    # handlers. That said, this could be refactored due to looping is needed now
    # for each task.
    - name: Create LXD containers
      community.general.lxd_container:
        name: item
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd
          alias: ubuntu/xenial/amd64
        url: https://192.168.100.149:8443
        trust_password: "Passw0rd!"
        profiles: ["default"]
      loop: "{{ groups['containers'] }}"

#     - name: Generate systemd container contents
#       ansible.builtin.command: |
#         debootstrap --include=systemd-container,sudo bullseye {{ item.path }}
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Start newly created systemd containers
#       ansible.builtin.command: |
#         machinectl start {{ item.item }}
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     # TODO(cavcrosby): this could be refactored due to each command needing the same
#     # boilerplate, but running everything in a shell module with a literal block
#     # scalar appeared to not work.
#     #
#     # inspired by:
#     # https://bbs.archlinux.org/viewtopic.php?id=237096
#     - name: Add ansible group
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "groupadd ansible"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Add ansible user
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "useradd --gid ansible --shell /bin/bash --create-home --home-dir /home/ansible ansible"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Configure ansible password
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "echo ansible:Passw0rd! | chpasswd"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Add ansible to sudoers
#       ansible.builtin.shell: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "echo 'ansible  ALL=(ALL:ALL) ALL' > /etc/sudoers.d/ansible"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

#     - name: Lock root account
#       ansible.builtin.command: |
#         systemd-run --machine {{ item.item }} /bin/sh -c "passwd --lock --delete root"
#       become: yes
#       when: item.changed
#       loop: "{{ create_systemd_containers_bases.results }}" # noqa 503

    # - name: Debug
    #   ansible.builtin.debug:
    #     var: hostvars[item]['type']
    #   loop: "{{ groups['containers'] }}"

# - name: Configure Container Nodes
#   hosts: altaria_containers
  
#   roles:
#     - altaria

#
# DISCUSS(cavcrosby): implement this play, essentially here is where each systemd
# container will be created and along with its appropriate .nspawn file.
