---
- name: Add systemd.unified_cgroup_hierarchy=0 to grub boot command(s)
  hosts: ctrservers
  become: true
  vars:
    default_grub_path: /etc/default/grub

  tasks:
    - name: Check if the default grub configuration exists
      ansible.builtin.stat:
        path: "{{ default_grub_path }}"
      register: default_grub_config_check

    - name: Initial check if systemd.unified_cgroup_hierarchy=0 is added to GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.lineinfile:
        state: absent
        path: "{{ default_grub_path }}"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
      check_mode: true
      changed_when: false
      register: line_check

    - name: Add systemd.unified_cgroup_hierarchy=0 to GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.import_role:
        name: common
        tasks_from: managed_lineinfile
      vars:
        path: "{{ default_grub_path }}"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
        line: "GRUB_CMDLINE_LINUX_DEFAULT=\"${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0\""
        line_identifier: "append GRUB_CMDLINE_LINUX_DEFAULT with systemd.unified_cgroup_hierarchy=0"
      when: default_grub_config_check.stat.exists

    - name: Update grub.cfg
      ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
      when:
        - default_grub_config_check.stat.exists
        - line_check.found == 0

    - name: Reboot ctrservers to have new boot parameter(s) take effect
      ansible.builtin.reboot:
      when: line_check.found == 0
