---
- name: Add systemd.unified_cgroup_hierarchy=0 to grub boot command(s)
  hosts: ctrservers
  become: true

  tasks:
    - name: Check if the default grub configuration exists
      ansible.builtin.stat:
        path: /etc/default/grub
      register: default_grub_config_check

    - name: Add systemd.unified_cgroup_hierarchy=0 to GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.import_role:
        name: common
        tasks_from: lbyl_lineinfile
      vars:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
        line: "\n# ANSIBLE MANAGED\nGRUB_CMDLINE_LINUX_DEFAULT=\"${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0\""
        line_identifier: "append GRUB_CMDLINE_LINUX_DEFAULT with systemd.unified_cgroup_hierarchy=0"
      when: default_grub_config_check.stat.exists

    - name: Update grub.cfg
      ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
      when: default_grub_config_check.stat.exists

    - name: Reboot ctrservers to have new boot parameter(s) take effect
      reboot:
