---
- name: Run convention tasks
  hosts: all
  tags: do_convention_tasks

  tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Install libvirt-python dependencies (debian-like)
      ansible.builtin.apt:
        name:
          - gcc
          - libvirt-dev
          - python3-dev
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: temp_dir

    - name: Setup the Python virtual environment
      ansible.builtin.include_role:
        name: python_virtualenv
      vars:
        python_virtualenv_name: foo
        python_virtualenvs_path: "{{ temp_dir.path }}"
        python_virtualenv_pkgs:
          - libvirt-python
