---
- name: Run convention tasks
  hosts: all
  tags: do_convention_tasks
  serial: 1
  vars_files:
    - foo.yml
  vars:
    foo: bar

  pre_tasks:
    - name: Foo
      ansible.builtin.debug:
        msg: bar

  roles:
    - foo

  tasks:
    - name: Bar
      ansible.builtin.debug:
        msg: bar

  handlers:
    - name: Baz
      ansible.builtin.debug:
        msg: bar
