---
- name: Remove cavcrosby-makefiles's installed GPG key
  ansible.builtin.file:
    path: "{{ cavcrosby_makefiles_keyring_install_path }}"
    state: absent
  become: true
  become_user: root

- name: Install cavcrosby-makefiles's GPG key
  ansible.builtin.shell: |
    gpg --batch --output {{ cavcrosby_makefiles_keyring_install_path }} --dearmor {{ cavcrosby_makefiles_keyring_download_path }}
  become: true
  become_user: root
