---
collections:
  - name: ansible.posix
    version: ==1.5.4

  - name: community.general
    version: ==9.0.1

  - name: community.libvirt
    version: ==1.3.0

  - name: kubernetes.core
    version: ==5.0.0
