---
collections:
  - name: ansible.posix
    version: ==1.5.4

  - name: community.general
    version: ==8.5.0

  - name: community.libvirt
    version: ==1.3.0

  - name: kubernetes.core
    version: ==3.1.0
