---
- name: Register the LXD altaria containers as inventory
  ansible.builtin.add_host:
    # The 'name' attribute makes Ansible happy, trying to combine
    # name/ansible_lxd_host into 'ansible_host' did not appear to work. For reference:
    # https://docs.ansible.com/ansible/latest/collections/community/general/lxd_connection.html
    #
    # Also inspired by:
    # https://www.reddit.com/r/ansible/comments/9b03l8/managing_lxd_containers_on_remote_machines/
    name: "{{ inventory_hostname }}:{{ item.name }}"
    lxd_container_type: "{{ item.type }}"
    ansible_lxd_remote: "{{ ansible_default_ipv4.address }}"
    ansible_lxd_host: "{{ item.name }}"
    jenkins_user: "{{ altaria_jenkins_user }}"
    jenkins_user_password: "{{ altaria_jenkins_system_user_password }}"
    jenkins_main_node_admin_id: "{{ jenkins_torkel_admin_id }}"
    jenkins_main_node_admin_password: "{{ jenkins_torkel_admin_password }}"
    jenkins_main_node_ipv4_addr: "{{ jenkins_torkel_ipv4_addr }}"
    jenkins_main_node_port: "{{ jenkins_torkel_port }}"
    jenkins_main_node_workingdir: "{{ jenkins_torkel_workingdir }}"
    jenkins_infrastructure_repo_tag: "{{ altaria_jenkins_infrastructure_repo_tag }}"
    pyenv_version: "{{ altaria_pyenv_version }}"
    ansible_connection: lxd
    groups: [lxd_containers]
  no_log: true
  changed_when: false
  when: item.type == "altaria"
