---
- name: Configure Calico networking (BGP) INPUT
  ansible.builtin.iptables:
    chain: INPUT
    destination_port: 179
    protocol: tcp
    jump: ACCEPT
    comment: (k8s) Calico networking BGP
  become: true
  notify:
    - Save the current iptables rules

- name: Configure Calico networking (BGP) OUTPUT
  ansible.builtin.iptables:
    chain: OUTPUT
    destination_port: 179
    protocol: tcp
    jump: ACCEPT
    comment: (k8s) Calico networking BGP
  become: true
  notify:
    - Save the current iptables rules

- name: Install the Calico CNI
  block:
    - name: Create the Calico Helm values file
      ansible.builtin.template:
        src: "{{ calico_helm_values_file_template }}"
        dest: "{{ calico_helm_values_file_path }}"
        mode: "600"
      vars:
        dockerhub_creds_secret_name: dockerhub-creds

    - name: Add the Calico Helm repo
      kubernetes.core.helm_repository:
        repo_name: projectcalico
        repo_url: https://projectcalico.docs.tigera.io/charts
      become: true

    - name: Deploy the Calico Helm chart inside the tigera-operator namespace
      kubernetes.core.helm:
        release_name: calico
        chart_ref: projectcalico/tigera-operator
        chart_version: "{{ calico_chart_version }}"
        release_namespace: tigera-operator
        create_namespace: true
        release_state: present
        values_files:
          - "{{ calico_helm_values_file_path }}"
      become: true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  vars:
    calico_helm_values_file_path: /tmp/{{ (calico_helm_values_file_template | basename | splitext)[:-1] | join('.') }}

- name: Install calicoctl
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/calico/releases/download/{{ calico_chart_version }}/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    mode: "755"
  become: true
