---
- name: Setup default legacy userland "iptables" tools
  block:
    - name: Install legacy iptables dependencies (debian-like)
      ansible.builtin.apt:
        name:
          - arptables
          - ebtables
          - iptables
          - iptables-persistent
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Setup legacy iptables
      community.general.alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy
      become: true

    - name: Setup legacy ip6tables
      community.general.alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy
      become: true

    - name: Setup legacy arptables
      community.general.alternatives:
        name: arptables
        path: /usr/sbin/arptables-legacy
      become: true

    - name: Setup legacy ebtables
      community.general.alternatives:
        name: ebtables
        path: /usr/sbin/ebtables-legacy
      become: true
