---
- name: Setup the Calico CNI
  block:
    - name: Add the Calico Helm repository
      kubernetes.core.helm_repository:
        repo_name: projectcalico
        repo_url: https://docs.tigera.io/calico/charts
      become: true

    - name: Deploy the Calico Helm chart inside the tigera-operator namespace
      kubernetes.core.helm:
        release_name: calico
        chart_ref: projectcalico/tigera-operator
        chart_version: "{{ calico_chart_version }}"
        release_namespace: tigera-operator
        create_namespace: true
        release_state: present
        values: "{{ lookup('ansible.builtin.template', calico_helm_values_file_template) | from_yaml }}"
      become: true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      vars:
        dockerhub_creds_secret_name: dockerhub-creds

- name: Install calicoctl
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/calico/releases/download/{{ calico_chart_version }}/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    checksum: sha256:22d7ba5547aff1b4202ddd55952c1e5b6e45e416cd79e1721438aab54a23324a
    mode: "755"
  become: true
