---
- name: Create the IRC system user group
  ansible.builtin.group:
    name: "{{ irc_system_user }}"
    state: present
  become: true

- name: Create the IRC system user
  ansible.builtin.user:
    name: "{{ irc_system_user }}"
    group: "{{ irc_system_user }}"
    state: present
    home: "{{ irc_system_user_home }}"
    shell: /bin/bash
  become: true

- name: Create the IRC system user's .ssh directory
  ansible.builtin.file:
    path: "{{ irc_system_user_home }}/.ssh"
    owner: "{{ irc_system_user }}"
    group: "{{ irc_system_user }}"
    state: directory
    mode: "700"
  become: true

- name: Create the authorized_keys file to enable SSH access as the IRC system user
  ansible.builtin.copy:
    dest: "{{ irc_system_user_home }}/.ssh/authorized_keys"
    owner: "{{ irc_system_user }}"
    group: "{{ irc_system_user }}"
    mode: "600"
    content: |
      {{ lookup('ansible.builtin.file', './ssh_keys/id_rsa_ron.pub') }}
      {{ lookup('ansible.builtin.file', './ssh_keys/id_rsa_roxanne.pub') }}
  become: true
