---
- name: Create the Jenkins namespace in the Kubernetes cluster
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ k8s_jenkins_instance_name }}"
    state: present
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Apply the Jenkins manifest to the Kubernetes cluster
  kubernetes.core.k8s:
    template: "{{ k8s_jenkins_manifest_template }}"
    state: present
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
