---
- name: Create the Jenkins namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ jenkins_instance_name }}"
    state: present
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Create the Jenkins manifest
  ansible.builtin.template:
    src: "{{ jenkins_manifest_template }}"
    dest: "{{ _jenkins_manifest_path }}"
    mode: "600"

- name: Apply the Jenkins manifest to the cluster
  kubernetes.core.k8s:
    src: "{{ _jenkins_manifest_path }}"
    state: present
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
