---
# which haproxy jinja template to use
haproxy_config_file_template: lb.cfg.j2

# evaluated jinja template filename on the target system
haproxy_config_target_file: "{{ (haproxy_config_file_template | basename | splitext)[:-1] | join('.') }}"

_haproxy_config_dir_path: /etc/haproxy.d

# Strips the config template of its final extension. For reference on where this
# idea was inspired from:
# https://stackoverflow.com/questions/41851418/ansible-roles-change-file-extension#answer-62443273
_haproxy_config_file_path: "{{ _haproxy_config_dir_path }}/{{ haproxy_config_target_file }}"
