---
# initial state of the VRRP instance
vrrp_state: MASTER

# network interface that VIPs will be bound to
vrrp_interface: eth0

# the keepalived cluster ID (should be different for clusters in the same subnet)
vrrp_virtual_router_id: 51

# value used when electing MASTER, highest priority wins
vrrp_priority: 50
vrrp_server_vip: 192.168.1.2

# which keepalived jinja template to use
keepalived_config_file_template: keepalived.conf.j2

# evaluated jinja template filename on the target system
keepalived_config_target_file: "{{ (keepalived_config_file_template | basename | splitext)[:-1] | join('.') }}"

# Health script used to ensure the VRRP node holding the virtual IP is still
# available.
keepalived_health_check_script_template: ""

# evaluated jinja template script name on the target system
keepalived_health_check_target_script: "{{ (keepalived_health_check_script_template | basename | splitext)[:-1] | join('.') }}"

_keepalived_health_check_script_path: /etc/keepalived/{{ keepalived_health_check_target_script }}
_keepalived_config_file_path: /etc/keepalived/{{ keepalived_config_target_file }}
