---
# initial state of the VRRP instance
keepalived_vrrp_state: MASTER

# network interface that VIPs will be bound to
keepalived_vrrp_interface: eth0

# the keepalived cluster ID (should be different for clusters in the same subnet)
keepalived_vrrp_virtual_router_id: 51

# value used when electing MASTER, highest priority wins
keepalived_vrrp_priority: 50
keepalived_vrrp_server_vip: 192.168.1.2

# which keepalived jinja template to use
keepalived_config_file_template: keepalived.conf.j2

# evaluated jinja template filename on the target system
keepalived_config_target_file: "{{ (keepalived_config_file_template | basename | splitext)[:-1] | join('.') }}"

# file that is used to save the current iptables rules
keepalived_iptables_rules_path: /etc/iptables/rules.v4

_keepalived_config_file_path: /etc/keepalived/{{ keepalived_config_target_file }}
