---
- name: Create the br_netfilter configuration file
  ansible.builtin.copy:
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "644"
    content: |
      #
      #
      # ANSIBLE MANAGED
      br_netfilter
  become: true
  notify:
    - Restart systemd-modules-load

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

# for reference on why this was needed:
# https://github.com/kubernetes/kubeadm/issues/1062
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#install-and-configure-prerequisites
- name: Configure required kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
  become: true
  loop:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1
