---
lxd_release_version: "4.0.8"
lxd_extracted_tarball_path: "/usr/local/src"

# TODO(cavcrosby): this will be overwritten at the playbook level. That said,
# handling this secret (and others) should be done in a more private/secure
# manner. For reference on some ideas:
# https://www.redhat.com/sysadmin/ansible-playbooks-secrets
lxd_trust_password: "Passw0rd!"


# TODO(cavcrosby): it is possible that LXD is installed with a user whose
# GOPATH is already set. This variable should respect that first and use the
# GOPATH already set. Using the hard-coded one as a default incase GOPATH is
# not set.
global_go_path: "/usr/local/share/go"

# The intention behind the wrapper is to have a place to set LD_LIBRARY_PATH
# before calling lxd. As this env var will be wiped by sudo, even if appended to
# env_keep in the sudoers file. If the wrapper path is to change, ensure the new
# wrapper path is before the GOPATH/bin dir on the PATH.
lxd_wrapper_path: "/usr/local/bin/lxd"

# TODO(cavcrosby): change the ipv4 address to a random private IP. Add the actual
# preseed to 'site.yaml'.
lxd_preseed: |
  config:
    core.https_address: {{ ansible_default_ipv4.address }}
    core.trust_password: true
  networks:
  - config:
      ipv4.address: 10.10.100.1/24
      ipv4.nat: "true"
      ipv6.address: fd42:cf87:377f:12aa::1/64
      ipv6.nat: "true"
    description: ""
    name: lxdbr0
    type: bridge
  storage_pools:
  - config:
      source: /var/lib/lxd/storage-pools/default
    description: ""
    name: default
    driver: dir
  profiles:
  - config: {}
    description: Default LXD profile
    devices:
      eth0:
        name: eth0
        network: lxdbr0
        type: nic
      root:
        path: /
        pool: default
        type: disk
    name: default

# The default bridge created when installing 'a' lxc package.
_default_lxc_bridge: lxcbr0

_lxd_data_dir: "/run/ansible/lxc-source"
_lxd_remote_preseed_path: "{{ _lxd_data_dir }}/lxd.yaml"
_running_lxd_remote_preseed_path: "{{ _lxd_data_dir }}/running-lxd.yaml"
_lxd_cgo_cflags: "-I{{ lxd_extracted_tarball_path }}/lxd-{{ lxd_release_version }}/vendor/raft/include/ -I{{ lxd_extracted_tarball_path }}/lxd-{{ lxd_release_version }}/vendor/dqlite/include/"
_lxd_cgo_ldflags: "-L{{ lxd_extracted_tarball_path }}/lxd-{{ lxd_release_version }}/vendor/raft/.libs/ -L{{ lxd_extracted_tarball_path }}/lxd-{{ lxd_release_version }}/vendor/dqlite/.libs/"
_lxd_cgo_ldflags_allow: "(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
_lxd_ld_library_path: "{{ lxd_extracted_tarball_path }}/lxd-{{ lxd_release_version }}/vendor/raft/.libs/:{{ lxd_extracted_tarball_path }}/lxd-{{ lxd_release_version }}/vendor/dqlite/.libs/"
