---
- name: Restart the keepalived service
  ansible.builtin.systemd_service:
    name: keepalived.service
    state: restarted
  become: true

- name: Save the current iptables rules
  community.general.iptables_state:
    path: "{{ keepalived_iptables_rules_path }}"
    state: saved
  become: true
