---
- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  become: true

- name: Save the current iptables rules
  community.general.iptables_state:
    path: "{{ keepalived_iptables_rules_path }}"
    state: saved
  become: true
