# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider "libvirt" do |domains|
        domains.driver = "kvm"
        domains.cpus = 1
        domains.memory = 2048
        domains.storage_pool_name = "default"
    end
end
