---
# used to determine what interface to listen for DHCP requests
dnsmasq_dhcp_listen_ipv4_addr: 192.168.1.2

# additional DHCP parameters
dnsmasq_dhcp_network_subnet_mask: 192.168.1.0/24
dnsmasq_dhcp_network_gateway_ipv4_addr: 192.168.1.1
dnsmasq_dhcp_lower_bound: 192.168.1.3
dnsmasq_dhcp_upper_bound: 192.168.1.255

# which dnsmasq (dhcp) jinja template to use
dnsmasq_dhcp_config_file_template: dhcp.conf.j2

# evaluated jinja template filename on the target system
dnsmasq_dhcp_config_target_file: "{{ (dnsmasq_dhcp_config_file_template | ansible.builtin.basename | ansible.builtin.splitext)[:-1] | join('.') }}"

_dnsmasq_dhcp_config_file_path: /etc/dnsmasq.d/{{ dnsmasq_dhcp_config_target_file }}
