---
# used to determine what interface to listen for DHCP requests
dhcp_listen_ipv4_addr: 127.0.0.1

# which dnsmasq jinja template to use
dhcp_config_file_template_name: dhcp.conf.j2

_dhcp_config_file_path: /etc/dnsmasq.d/dhcp.conf
