---
# used to determine what interface to listen for DNS requests
dnsmasq_dns_listen_ipv4_addr: 127.0.0.2

# subnet for the domain
dnsmasq_dns_subnet: 127.0.0.0/8

# specify the DNS domain for DHCP
dnsmasq_dns_local_domain: ansible.localhost

# which dnsmasq (dns) jinja template to use
dnsmasq_dns_config_file_template: dns.conf.j2

# evaluated jinja template filename on the target system
dnsmasq_dns_config_target_file: "{{ (dnsmasq_dns_config_file_template | ansible.builtin.basename | ansible.builtin.splitext)[:-1] | join('.') }}"

_dnsmasq_dns_config_file_path: /etc/dnsmasq.d/{{ dnsmasq_dns_config_target_file }}
