---
- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  become: true

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: restarted
  become: true
