---
- name: Configure VRRP ports
  ansible.builtin.iptables:
    chain: INPUT
    destination_port: 112
    protocol: tcp
    jump: ACCEPT
  become: true
  notify: Save the current iptables rules

- name: Update apt's package index (debian-like)
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family | lower == "debian"

- name: Install keepalived (debian-like)
  ansible.builtin.apt:
    name:
      - keepalived
    state: present
  become: true
  when: ansible_os_family | lower == "debian"

- name: Create the keepalived configuration file
  ansible.builtin.template:
    src: "{{ keepalived_config_file_template }}"
    dest: "{{ _keepalived_config_file_path }}"
    mode: "644"
  become: true
  notify: Restart keepalived

- name: Alter the keepalived configuration to use a non-default configuration path
  ansible.builtin.blockinfile:
    state: present
    path: /etc/default/keepalived
    marker: "# {mark} ANSIBLE MANAGED -- use non-default keepalived config path"
    prepend_newline: true
    block: |
      DAEMON_ARGS="--use-file={{ _keepalived_config_file_path }}"
  become: true
  notify: Restart keepalived

- name: Enable the keepalived service
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: started
  become: true
