---
- name: Stop the haproxy service
  ansible.builtin.systemd_service:
    name: haproxy.service
    state: stopped
  become: true

- name: Restart the haproxy service
  ansible.builtin.systemd_service:
    name: haproxy.service
    state: restarted
  become: true
