---
- name: append {{ block_file_path }} with overarching ANSIBLE MANAGED header
  ansible.builtin.import_role:
    name: common
    tasks_from: lbyl_lineinfile
  vars:
    path: "{{ block_file_path }}"
    regexp: '^### ANSIBLE MANAGED$'
    line: "\n### ANSIBLE MANAGED\n"
    line_identifier: "overarching ANSIBLE MANAGED header"

- name: Check if {{ block_identifier }} already in {{ block_file_path }}
  ansible.builtin.blockinfile:
    state: absent
    path: "{{ block_file_path }}"
    block: "{{ block_text }}"
  check_mode: true
  changed_when: false
  register: block_check

- name: Append {{ block_file_path }} with {{ block_identifier }}
  ansible.builtin.blockinfile:
    state: present
    path: "{{ block_file_path }}"
    block: "{{ block_text }}"
  # blockinfile's check_mode does not return a 'found' attribute like lineinfile's
  # check_mode. This alternative could be better.
  when: block_check.msg | length == 0

- name: Insert newline after block
  ansible.builtin.shell: echo "" >> "{{ block_file_path }}"
  when: block_check.msg | length == 0
