# inspired by:
# https://stackoverflow.com/questions/29075287/ansible-insert-line-if-not-exists#answer-62609075
- name: Check if {{ line_identifier }} already in {{ path }}
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ path }}"
    regexp: "{{ regexp }}"
  check_mode: true
  changed_when: false
  register: line_check

- name: Append {{ path }} with {{ line_identifier }}
  ansible.builtin.lineinfile:
    path: "{{ path }}"
    regexp: "{{ regexp }}"
    line: "{{ line }}"
  when: line_check.found == 0
