---
# inspired by:
# https://stackoverflow.com/questions/29075287/ansible-insert-line-if-not-exists#answer-62609075
- name: Check if {{ line_identifier }} already in {{ path }}
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ path }}"
    regexp: "{{ regexp }}"
  check_mode: true
  changed_when: false
  register: line_check

- name: Check if Ansible managed header already in {{ path }}
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ path }}"
    regexp: '^### ANSIBLE MANAGED$'
  check_mode: true
  changed_when: false
  register: ansible_managed_header_check
  when: line_check.found == 0

- name: Append {{ path }} with Ansible managed header
  ansible.builtin.lineinfile:
    state: present
    path: "{{ path }}"
    regexp: '^### ANSIBLE MANAGED$'
    line: "\n### ANSIBLE MANAGED\n"
  when:
    - line_check.found == 0
    - ansible_managed_header_check.found == 0

- name: Append {{ path }} with {{ line_identifier }}
  ansible.builtin.lineinfile:
    state: present
    path: "{{ path }}"
    regexp: "{{ regexp }}"
    line: "{{ line }}"
