---
- name: Update apt's package index
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family | lower == "debian"

- name: Install dnsmasq (debian-like)
  ansible.builtin.apt:
    name:
      - dnsmasq
    state: present
  become: true
  when: ansible_os_family | lower == "debian"

- name: Create the dnsmasq (dns) configuration file
  ansible.builtin.template:
    src: "{{ dnsmasq_dns_config_file_template }}"
    dest: "{{ _dnsmasq_dns_config_file_path }}"
    mode: "644"
    validate: dnsmasq --test --conf-file=%s
  become: true
  notify:
    - Restart dnsmasq

- name: Enable the dnsmasq service
  ansible.builtin.service:
    name: dnsmasq
    enabled: true
    state: started
  become: true
