---
- name: Restart the fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true

- name: Restart the sshd service
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
