---
- name: Start and enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: started
  become: true

- name: Remove the networking service's interfaces file (debian-like)
  ansible.builtin.file:
    path: /etc/network/interfaces
    state: absent
  become: true
  when: ansible_os_family | lower == "debian"

- name: Stop and disable the networking service (debian-like)
  ansible.builtin.systemd:
    name: networking
    enabled: false
    state: stopped
  become: true
  when: ansible_os_family | lower == "debian"

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: restarted
  become: true
