---
- name: Enable and start the systemd-networkd service
  ansible.builtin.systemd_service:
    name: systemd-networkd.service
    enabled: true
    state: started
  become: true

- name: Remove the networking service's interfaces file (debian-like)
  ansible.builtin.file:
    path: /etc/network/interfaces
    state: absent
  become: true
  when: ansible_os_family | lower == "debian"

- name: Stop and disable the networking service (debian-like)
  ansible.builtin.systemd_service:
    name: networking.service
    enabled: false
    state: stopped
  become: true
  when: ansible_os_family | lower == "debian"

- name: Restart systemd-networkd service
  ansible.builtin.systemd_service:
    name: systemd-networkd.service
    enabled: true
    state: restarted
  become: true

- name: Start reload-udev-offline timer
  ansible.builtin.systemd_service:
    name: reload-udev-offline.timer
    state: started
  become: true
  listen: Reload udev while offline

- name: Wait for hosts to become reachable
  ansible.builtin.wait_for_connection:
    delay: 10
  listen: Reload udev while offline
