---
- name: Start and enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: started
  become: true

- name: Remove Debian's networking daemon interfaces file
  ansible.builtin.file:
    path: /etc/network/interfaces
    state: absent
  when: ansible_distribution | lower == "debian"
  become: true

- name: Stop and disable Debian networking daemon
  ansible.builtin.systemd:
    name: networking
    enabled: false
    state: stopped
  when: ansible_distribution | lower == "debian"
  become: true

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: restarted
  become: true
