---
- name: Remove Helm's installed GPG key
  ansible.builtin.file:
    path: "{{ _helm_keyring_install_path }}"
    state: absent
  become: true

# --batch option is needed for gpg due to odd "gpg: cannot open '/dev/tty'" error.
# For reference:
# https://github.com/pipech/erpnext-docker-debian/issues/26
- name: Install Helm's GPG key
  ansible.builtin.shell: |
    gpg --batch --output {{ _helm_keyring_install_path }} --dearmor {{ _helm_keyring_download_path }}
  become: true
