---
- name: Create customizations on top of the default cloud-init configurations
  ansible.builtin.template:
    src: cloud-init.cfg.j2
    dest: /etc/cloud/cloud.cfg.d/99_{{ inventory_hostname }}.cfg
    mode: "644"
  become: true

- name: Rerun particular cloud-init modules
  ansible.builtin.shell: |
    set -e
    cloud-init single --name "cc_set_hostname"
    cloud-init single --name "cc_update_etc_hosts"
  changed_when: false
  become: true
