---
- name: Create a user with my typical username
  ansible.builtin.user:
    name: "{{ typical_user }}"
    state: present
    home: /home/{{ typical_user }}
    shell: /bin/bash
    password: "{{ typical_user_password }}"
  become: yes

- name: Add {{ typical_user }} to "sudo" group
  ansible.builtin.user:
    append: yes
    groups: sudo
    name: "{{ typical_user }}"
  become: yes

- name: Set the hostname to the instance name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: Create {{ typical_user }}'s .ssh directory
  ansible.builtin.file:
    path: "{{ typical_user_home }}/.ssh"
    owner: "{{ typical_user }}"
    group: "{{ typical_user }}"
    state: directory
    mode: "700"
  become: yes

- name: Add the public SSH key to manage instance as {{ typical_user }}
  ansible.builtin.copy:
    dest: "{{ typical_user_home }}/.ssh/authorized_keys"
    src: "{{ typical_user_pubkey_controller_path }}"
    owner: "{{ typical_user }}"
    group: "{{ typical_user }}"
    mode: "600"
  become: yes
