---
- name: Create customizations on top of the default cloud-init configurations
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/99_{{ inventory_hostname }}.cfg
    mode: "644"
    content: |
      #
      #
      # ANSIBLE MANAGED

      hostname: "{{ inventory_hostname | capitalize }}"
      manage_etc_hosts: true
  become: true

- name: Rerun particular cloud-init modules
  ansible.builtin.shell: |
    cloud-init single --name cc_set_hostname
    cloud-init single --name cc_update_etc_hosts
  become: true
  changed_when: false
