---
- name: Install and configure dnsmasq (dhcp)
  hosts: dhcp_servers
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Setup systemd-networkd networking
      block:
        - name: Setup systemd-networkd networking
          ansible.builtin.include_role:
            name: systemd_networkd
          vars:
            systemd_networkd_files:
              - filename: "{{ dhcp_listen_network_interface_name }}.link"
                Match:
                  MACAddress: "{{ dhcp_listen_network_interface_mac_addr }}"
                Link:
                  NamePolicy: keep

              - filename: "{{ dhcp_listen_network_interface_name }}.network"
                Match:
                  Name: "{{ dhcp_listen_network_interface_name }}"
                Network:
                  Address: "{{ dhcp_listen_ipv4_addr }}"
                  Gateway: "{{ dhcp_network_gateway_ipv4_addr }}"

    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - dnsmasq_dhcp

- name: Install and configure dnsmasq (dns)
  hosts: dns_servers
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Setup systemd-networkd networking
      block:
        - name: Setup systemd-networkd networking
          ansible.builtin.include_role:
            name: systemd_networkd
          vars:
            systemd_networkd_files:
              - filename: "{{ dns_listen_network_interface_name }}.link"
                Match:
                  MACAddress: "{{ dns_listen_network_interface_mac_addr }}"
                Link:
                  NamePolicy: keep

              - filename: "{{ dns_listen_network_interface_name }}.network"
                Match:
                  Name: "{{ dns_listen_network_interface_name }}"
                Network:
                  Address: "{{ dns_listen_ipv4_addr }}"
                  Gateway: "{{ dns_network_gateway_ipv4_addr }}"

    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - dnsmasq_dns
