---
- name: Install and configure dnsmasq (dhcp)
  hosts: dhcp_servers
  tags: install_dnsmasq_dhcp
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Setup systemd-networkd networking
      ansible.builtin.include_role:
        name: systemd_networkd
      vars:
        systemd_networkd_files:
          - filename: "{{ dhcp_listen_network_interface_name }}.link"
            Match:
              MACAddress: "{{ dhcp_listen_network_interface_mac_addr }}"
            Link:
              NamePolicy: keep

          - filename: "{{ dhcp_listen_network_interface_name }}.network"
            Match:
              Name: "{{ dhcp_listen_network_interface_name }}"
            Network:
              Address: "{{ dhcp_listen_ipv4_addr }}/{{ dhcp_listen_cidr_prefix }}"
              Gateway: "{{ dhcp_network_gateway_ipv4_addr }}"

    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - role: dnsmasq_dhcp
      vars:
        dhcp_network_subnet_mask: "{{ homelab_network_subnet }}"
        dhcp_network_gateway_ipv4_addr: "{{ homelab_network_gateway_ipv4_addr }}"
        dhcp_lower_bound: "{{ homelab_network_lower_bound }}"
        dhcp_upper_bound: "{{ homelab_network_upper_bound }}"
        dhcp_config_file_template: dhcp.conf.j2

- name: Install and configure dnsmasq (dns)
  hosts: dns_servers
  tags: install_dnsmasq_dns
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Setup systemd-networkd networking
      ansible.builtin.include_role:
        name: systemd_networkd
      vars:
        systemd_networkd_files:
          - filename: "{{ dns_listen_network_interface_name }}.link"
            Match:
              MACAddress: "{{ dns_listen_network_interface_mac_addr }}"
            Link:
              NamePolicy: keep

          - filename: "{{ dns_listen_network_interface_name }}.network"
            Match:
              Name: "{{ dns_listen_network_interface_name }}"
            Network:
              Address: "{{ dns_listen_ipv4_addr }}/{{ dns_listen_cidr_prefix }}"
              Gateway: "{{ dns_network_gateway_ipv4_addr }}"

    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - role: dnsmasq_dns
      vars:
        dns_subnet: "{{ homelab_network_subnet }}"
        dns_network_gateway_ipv4_addr: "{{ homelab_network_gateway_ipv4_addr }}"
        dns_local_domain: "{{ homelab_network_domain }}"
        dns_config_file_template: dns.conf.j2
