---
- name: Install and configure dnsmasq (dhcp)
  hosts: dhcp_servers
  tags: install_dnsmasq_dhcp
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

    - name: Setup systemd-networkd networking
      ansible.builtin.include_role:
        name: systemd_networkd
      vars:
        systemd_networkd_files: "{{ dhcp_systemd_networkd_files }}"

  roles:
    - role: dnsmasq_dhcp

- name: Install and configure dnsmasq (dns)
  hosts: dns_servers
  tags: install_dnsmasq_dns
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - role: dnsmasq_dns

- name: Install and configure haproxy
  hosts: load_balancers
  tags: install_haproxy_load_balancer
  vars_files:
    - "{{ network_configs_path }}"

  roles:
    - haproxy
