---
- name: Install and configure dnsmasq (dhcp)
  hosts: dhcp_servers
  tags: install_dnsmasq_dhcp
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Setup systemd-networkd networking
      ansible.builtin.include_role:
        name: systemd_networkd
      vars:
        systemd_networkd_files: "{{ dhcp_systemd_networkd_files }}"

  roles:
    - role: dnsmasq_dhcp
      vars:
        dhcp_config_target_file: homelab-dhcp.conf
