---
- name: Install and configure dnsmasq (for dhcp)
  hosts: dhcp_servers
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Setup systemd-networkd networking
      block:
        - name: Setup systemd-networkd networking
          ansible.builtin.include_role:
            name: systemd_networkd
          vars:
            systemd_networkd_files:
              - filename: "{{ listen_network_interface_name }}.link"
                Match:
                  MACAddress: "{{ listen_network_interface_mac_addr }}"
                Link:
                  NamePolicy: keep

              - filename: "{{ listen_network_interface_name }}.network"
                Match:
                  Name: "{{ listen_network_interface_name }}"
                Network:
                  Address: "{{ dhcp_server1_ipv4_addr }}"
                  Gateway: "{{ homelab_network_gateway_ipv4_addr }}"

  roles:
    - dnsmasq_dhcp
