---
- name: Install and configure dnsmasq (dhcp)
  hosts: dhcp_servers
  tags: install_dnsmasq_dhcp
  vars_files:
    - "{{ network_configs_path }}"

  roles:
    - role: dnsmasq_dhcp
      vars:
        dhcp_config_target_file: homelab-dhcp.conf
