---
- name: Install and configure dnsmasq (dns)
  hosts: dns_servers
  tags: install_dnsmasq_dns
  vars_files:
    - "{{ network_configs_path }}"

  roles:
    - role: dnsmasq_dns
      vars:
        dns_config_target_file: homelab-dns.conf
