---
- name: Perform customizations of lightsail instances
  hosts: irc_clients
  vars_files:
    - ./vars/ansible_secrets.yaml

  roles:
    - lightsail

- name: Install and configure WeeChat
  hosts: irc_clients

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: yes
      become: yes

  roles:
    - weechat
    
  tasks:
    - name: Install "nice to haves"
      ansible.builtin.apt:
        name:
          - tmux
        state: present
      become: yes
