---
- name: Perform setup for irc_client
  hosts: irc_clients
  tags: do_irc_client_setup

  pre_tasks:
    - name: Update apt's package index (debian-like)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Install tmux (debian-like)
      ansible.builtin.apt:
        name:
          - tmux
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

- name: Install and configure WeeChat
  hosts: irc_clients
  tags: install_weechat
  vars:
    irc_user: weechat
    irc_user_home: /home/{{ irc_user }}
    weechat_certs_directory: "{{ irc_user_home }}/.weechat/certs"

  pre_tasks:
    - name: Update apt's package index (debian-like)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Setup the IRC user
      ansible.builtin.import_tasks: ./tasks/setup_irc_user.yml

    - name: Install WeeChat (debian-like)
      ansible.builtin.apt:
        name:
          - weechat
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create WeeChat's certificates directory
      ansible.builtin.file:
        path: "{{ weechat_certs_directory }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        state: directory
        mode: "775"
      become: true

    - name: Add the WeeChat certificates
      ansible.builtin.copy:
        dest: "{{ weechat_certs_directory }}/{{ item | basename }}"
        src: "{{ item }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        mode: "600"
      become: true
      loop:
        - ./certs/liberachat.pem
        - ./certs/oftc.pem

- name: Perform lightsail customizations
  hosts: lightsail_instances
  tags: do_lightsail_customizations

  tasks:
    - name: Update apt's package index (debian-like)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Install fail2ban (debian-like)
      ansible.builtin.apt:
        name:
          - fail2ban
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the local fail2ban sshd jail configuration file
      ansible.builtin.template:
        src: f2b-sshd.local.j2
        dest: /etc/fail2ban/jail.d/00_sshd.local
        mode: "644"
      become: true
      notify: Restart the fail2ban service

    - name: Compile glibc's C.UTF-8 locale (debian-like)
      community.general.locale_gen:
        name: C.UTF-8
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Set the locale to glibc's C.UTF-8
      ansible.builtin.command: localectl set-locale "C.UTF-8"
      changed_when: "'C.UTF-8' != ansible_env['LANG']"
      become: true

    - name: Lockdown the root account
      ansible.builtin.user:
        name: root
        state: present
        password: !
        password_lock: true
      become: true

    - name: Set PermitRootLogin to no for the SSH daemon
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: ^#\s*PermitRootLogin\s+prohibit-password$
        replace: PermitRootLogin no
      become: true
      notify: Restart the sshd service

    - name: Create customizations on top of the default cloud-init configurations
      ansible.builtin.template:
        src: lightsail-cloud-init.cfg.j2
        dest: /etc/cloud/cloud.cfg.d/99_{{ inventory_hostname }}.cfg
        mode: "644"
      become: true

    - name: Rerun particular cloud-init modules
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -eo pipefail
          cloud-init single --name "cc_set_hostname"
          cloud-init single --name "cc_update_etc_hosts"
      changed_when: false
      become: true

  handlers:
    - name: Restart the fail2ban service
      ansible.builtin.service:
        name: fail2ban
        state: restarted
      become: true

    - name: Restart the sshd service
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true
