---
- name: Perform customizations of lightsail instances
  hosts: irc_clients
  vars_files:
    - vars/ansible_secrets.yaml

  roles:
    - lightsail

- name: Install and configure WeeChat
  hosts: irc_clients

  roles:
    - weechat
