---
- name: Perform initial setup for irc_client
  hosts: irc_clients
  vars_files:
    - ./vars/ansible_secrets.yml

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true

  tasks:
    - name: Create the irc_user
      ansible.builtin.user:
        name: "{{ irc_user }}"
        state: present
        home: "{{ irc_user_home }}"
        shell: /bin/bash
        password: "{{ irc_user_password }}"
      become: true

    - name: Add the irc_user to "sudo" group
      ansible.builtin.user:
        append: true
        groups: sudo
        name: "{{ irc_user }}"
      become: true

    - name: Create irc_user's .ssh directory
      ansible.builtin.file:
        path: "{{ irc_user_home }}/.ssh"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        state: directory
        mode: "700"
      become: true

    - name: Add the public SSH key to manage machine as irc_user
      ansible.builtin.copy:
        dest: "{{ irc_user_home }}/.ssh/authorized_keys"
        src: "{{ irc_user_ssh_pubkey_controller_path }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        mode: "600"
      become: true

- name: Install and configure WeeChat
  hosts: irc_clients

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true

  roles:
    - role: weechat
      vars:
        weechat_user: "{{ irc_user }}"
        weechat_tls_cert_controller_paths: "{{ irc_weechat_tls_cert_controller_paths }}"
    
  tasks:
    - name: Install "nice to haves"
      ansible.builtin.apt:
        name:
          - tmux
        state: present
      become: true

- name: Perform lightsail customizations
  hosts: lightsail_instances

  roles:
    - lightsail
