---
- name: Perform initial setup for irc_client
  hosts: irc_clients
  tags: initial_irc_client_setup

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Install tmux (debian-like)
      ansible.builtin.apt:
        name:
          - tmux
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

- name: Install and configure WeeChat
  hosts: irc_clients
  tags: install_weechat
  vars:
    irc_system_user: weechat
    irc_system_user_home: /home/{{ irc_system_user }}
    weechat_certs_directory: "{{ irc_system_user_home }}/.weechat/certs"

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Setup the IRC system user
      ansible.builtin.import_tasks: ./tasks/setup_irc_sysuser.yml

    - name: Install WeeChat (debian-like)
      ansible.builtin.apt:
        name:
          - weechat
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create WeeChat's certificates directory
      ansible.builtin.file:
        path: "{{ weechat_certs_directory }}"
        owner: "{{ irc_system_user }}"
        group: "{{ irc_system_user }}"
        state: directory
        mode: "775"
      become: true

    - name: Add the WeeChat certificates
      ansible.builtin.copy:
        dest: "{{ weechat_certs_directory }}/{{ item | basename }}"
        src: "{{ item }}"
        owner: "{{ irc_system_user }}"
        group: "{{ irc_system_user }}"
        mode: "600"
      become: true
      loop:
        - ./certs/libera.pem

- name: Perform lightsail customizations
  hosts: lightsail_instances
  tags: customize_lightsail

  roles:
    - lightsail
