---
- name: Perform initial setup for irc_client
  hosts: irc_clients
  tags: initial_irc_client_setup
  vars_files:
    - ./vars/ansible_secrets.yml

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Install "nice to haves" (debian-like)
      ansible.builtin.apt:
        name:
          - tmux
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the irc_user
      ansible.builtin.user:
        name: "{{ irc_user }}"
        state: present
        home: "{{ irc_user_home }}"
        shell: /bin/bash
        password: "{{ irc_user_password }}"
      become: true

    - name: Add the irc_user to "sudo" group
      ansible.builtin.user:
        append: true
        groups: sudo
        name: "{{ irc_user }}"
      become: true

    - name: Create irc_user's .ssh directory
      ansible.builtin.file:
        path: "{{ irc_user_home }}/.ssh"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        state: directory
        mode: "700"
      become: true

    - name: Add the public SSH key to manage machine as irc_user
      ansible.builtin.copy:
        dest: "{{ irc_user_home }}/.ssh/authorized_keys"
        src: "{{ irc_user_ssh_pubkey_controller_path }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        mode: "600"
      become: true

- name: Install and configure WeeChat
  hosts: irc_clients
  tags: install_weechat
  vars:
    weechat_certs_directory: "{{ irc_user_home }}/.weechat/certs"

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Install WeeChat (debian-like)
      ansible.builtin.apt:
        name:
          - weechat
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create WeeChat's certificates directory
      ansible.builtin.file:
        path: "{{ weechat_certs_directory }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        state: directory
        mode: "775"
      become: true

    - name: Add the WeeChat certificates
      ansible.builtin.copy:
        dest: "{{ weechat_certs_directory }}/{{ item | basename }}"
        src: "{{ item }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        mode: "600"
      become: true
      loop: "{{ irc_weechat_tls_cert_controller_paths }}"

- name: Perform lightsail customizations
  hosts: lightsail_instances
  tags: customize_lightsail

  roles:
    - lightsail
