---
- name: Perform setup for irc_client
  hosts: irc_clients
  tags: do_irc_client_setup

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Install tmux (debian-like)
      ansible.builtin.apt:
        name:
          - tmux
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

- name: Install and configure WeeChat
  hosts: irc_clients
  tags: install_weechat
  vars:
    irc_user: weechat
    irc_user_home: /home/{{ irc_user }}
    weechat_certs_directory: "{{ irc_user_home }}/.weechat/certs"

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

  tasks:
    - name: Setup the IRC user
      ansible.builtin.import_tasks: ./tasks/setup_irc_user.yml

    - name: Install WeeChat (debian-like)
      ansible.builtin.apt:
        name:
          - weechat
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create WeeChat's certificates directory
      ansible.builtin.file:
        path: "{{ weechat_certs_directory }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        state: directory
        mode: "775"
      become: true

    - name: Add the WeeChat certificates
      ansible.builtin.copy:
        dest: "{{ weechat_certs_directory }}/{{ item | basename }}"
        src: "{{ item }}"
        owner: "{{ irc_user }}"
        group: "{{ irc_user }}"
        mode: "600"
      become: true
      loop:
        - ./certs/liberachat.pem
        - ./certs/oftc.pem

- name: Perform lightsail customizations
  hosts: lightsail_instances
  tags: do_lightsail_customizations

  roles:
    - lightsail
