---
- name: Install Helm charts
  hosts: k8s_first_controllers
  tags: install_k8s_first_controller_helm_charts
  vars_files:
    - ./vars/k8s_software_versions.yml

  tasks:
    - name: Add the Ingress NGINX Helm repo
      kubernetes.core.helm_repository:
        repo_name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
      become: true

    - name: Deploy the Ingress NGINX Helm chart inside the ingress-nginx namespace
      kubernetes.core.helm:
        release_name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        chart_version: "{{ ingress_nginx_chart_version }}"
        release_namespace: ingress-nginx
        create_namespace: true
        release_state: present
      become: true
