---
- name: Perform initial setup for k8s_controller
  hosts: k8s_controllers
  tags: do_initial_k8s_controller_setup

  roles:
    - k8s_node

  tasks:
    - name: Setup the Python virtual environment
      ansible.builtin.include_role:
        name: python_virtualenv
      vars:
        python_virtualenv_name: "{{ ansible_user_python_virtualenv_name }}"
        python_virtualenv_path: "{{ ansible_user_python_virtualenvs_path }}"
        python_virtualenv_pkgs:
          - kubernetes
          - psutil
          - pyyaml

    - name: Add sourcing of the Python virtual environment
      ansible.builtin.blockinfile:
        state: present
        path: "{{ ansible_user_home }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED -- source the python virtualenv"
        prepend_newline: true
        block: |
          source "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/activate"

    - name: Setup legacy iptables
      ansible.builtin.import_tasks: ./tasks/setup_legacy_iptables.yml

- name: Perform initial setup for k8s_controller (poseidon)
  hosts: k8s_controllers:&poseidon
  tags: do_initial_poseidon_k8s_controller_setup
  vars_files:
    - "{{ network_configs_path }}"
    - "{{ k8s_software_versions_file }}"
  vars:
    containerd_deb: containerd_{{ containerd_version }}_amd64.deb

  pre_tasks:
    - name: Update apt's package index (debian-like)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Copy over the local containerd package (debian-like)
      ansible.builtin.copy:
        dest: /tmp/{{ containerd_deb }}
        src: "{{ containerd_deb }}"
        mode: "755"
      when: ansible_os_family | lower == "debian"

    - name: Install containerd (debian-like)
      ansible.builtin.apt:
        deb: /tmp/{{ containerd_deb }}
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Register the containerd configuration file
      ansible.builtin.stat:
        path: /etc/containerd/config.toml
        checksum_algorithm: sha256
      register: current_containerd_config_inode

    - name: Create the containerd configuration file
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -eo pipefail
          containerd config default > "{{ current_containerd_config_inode.stat.path }}"
          sed \
            --in-place \
            "s/SystemdCgroup = false/SystemdCgroup = true/" \
            "{{ current_containerd_config_inode.stat.path }}"

          sha256sum "{{ current_containerd_config_inode.stat.path }}" | awk -F " " '{ print $1 }'
      changed_when: current_containerd_config_inode.stat.checksum != containerd_config_checksum.stdout
      become: true
      register: containerd_config_checksum
      notify: Restart the containerd service

    - name: Prevent containerd from being upgraded (debian-like)
      ansible.builtin.dpkg_selections:
        name: containerd
        selection: hold
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the Kubernetes certificates directory
      ansible.builtin.file:
        path: "{{ k8s_cert_dir_path }}"
        recurse: true
        state: directory
      become: true

    - name: Copy the self-signed CA key into the Kubernetes certificate directory
      ansible.builtin.copy:
        dest: "{{ k8s_cert_dir_path }}/ca.key"
        src: rsa_keys/{{ ca_key }}
        mode: "600"
      become: true

    - name: Copy the self-signed CA certificate into the Kubernetes certificate directory
      ansible.builtin.copy:
        dest: "{{ k8s_root_cacert_path }}"
        src: certs/{{ ca_cert }}
        mode: "644"
      become: true

    - name: Register the self-signed CA certificate file inode
      ansible.builtin.stat:
        path: "{{ k8s_root_cacert_path }}"
      register: k8s_root_cacert_inode

    - name: Register the modification time of the self-signed CA certificate
      ansible.builtin.set_fact:
        initial_k8s_root_cacert_mtime: "{{ k8s_root_cacert_inode.stat.mtime }}"

    - name: Configure firewall for the particular Calico deployment
      ansible.builtin.import_tasks: ./tasks/config_fw_calico.yml

    - name: Install etcdctl
      vars:
        etcd_tarball: etcd-{{ etcdctl_version }}-linux-amd64.tar.gz
        etcd_download_path: /tmp/{{ etcd_tarball }}
        # regexp was inspired by:
        # https://stackoverflow.com/questions/61930563/extract-file-names-without-extension-ansible#answer-61931335
        strip_exts_regexp: ^(.*v\d+\.\d+\.\d+[^\.]*).*
      block:
        - name: Download the etcd tarball
          ansible.builtin.get_url:
            url: https://github.com/etcd-io/etcd/releases/download/{{ etcdctl_version }}/{{ etcd_tarball }}
            dest: "{{ etcd_download_path }}"
            checksum: sha256:f2ff0cb43ce119f55a85012255609b61c64263baea83aa7c8e6846c0938adca5..
            mode: "755"

        - name: Extract the etcd tarball into the desired directory
          ansible.builtin.unarchive:
            src: "{{ etcd_download_path }}"
            dest: "{{ etcd_download_path | ansible.builtin.dirname }}"
            remote_src: true

        - name: Install etcdctl into a accessible directory in the PATH
          ansible.builtin.copy:
            dest: /usr/local/bin/etcdctl
            src: "{{ etcd_download_path | ansible.builtin.regex_replace(strip_exts_regexp, '\\1') }}/etcdctl"
            mode: "755"
            remote_src: true
          become: true

  roles:
    - role: haproxy
      vars:
        haproxy_config_target_file: haproxy.cfg

    - role: keepalived
      vars:
        keepalived_config_file_template: poseidon/k8s-keepalived.conf.j2
        keepalived_config_target_file: keepalived.conf
        keepalived_iptables_rules_path: /etc/iptables/rules.v4

    - role: helm
      vars:
        helm_gpg_sha256_checksum: d8d0edbdc72338073b7b126be1454c7ebd29bf0da2f64fba87b82d2ae528626d.

    - k8s_kubeadm

  handlers:
    - name: Save the current iptables rules
      community.general.iptables_state:
        path: "{{ k8s_control_plane_iptables_rules_path }}"
        state: saved
      become: true

    - name: Restart the containerd service
      ansible.builtin.systemd_service:
        name: containerd.service
        state: restarted
      become: true

- name: Setup Kubernetes control planes (first control-planes)
  hosts: k8s_first_controllers
  tags: configure_as_k8s_first_controller
  vars_files:
    - "{{ network_configs_path }}"
    - "{{ k8s_software_versions_file }}"
    - ansible_secrets.yml
  vars:
    k8s_cert_dir_path: /etc/kubernetes/pki
    ansible_python_interpreter: "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/python"

  roles:
    - role: k8s_control_plane
      become: true

- name: Setup Kubernetes control planes (first control-planes) (poseidon)
  hosts: k8s_first_controllers:&poseidon
  tags: configure_as_poseidon_k8s_first_controller
  vars_files:
    - "{{ k8s_software_versions_file }}"
    - ansible_secrets.yml
  vars:
    ansible_python_interpreter: "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/python"

  pre_tasks:
    - name: Setup the Calico CNI
      ansible.builtin.import_tasks: ./tasks/setup_calico.yml

- name: Setup Kubernetes control planes (high availability)
  hosts: k8s_ha_controllers
  tags: configure_as_k8s_ha_controller
  serial: 1
  vars_files:
    - "{{ network_configs_path }}"
    - ansible_secrets.yml
  vars:
    ansible_python_interpreter: "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/python"

  roles:
    - role: k8s_control_plane
      become: true

- name: Setup Kubernetes control planes (high availability) (poseidon)
  hosts: k8s_ha_controllers:&poseidon
  tags: configure_as_poseidon_k8s_ha_controller

  tasks:
    - name: Check the modification time of the self-signed CA certificate
      ansible.builtin.stat:
        path: "{{ k8s_root_cacert_path }}"
      # Without casting the current inode's modification time to a str, it would have
      # always returned a status of changed.
      changed_when:
        - initial_k8s_root_cacert_mtime is defined
        - initial_k8s_root_cacert_mtime != (k8s_root_cacert_inode.stat.mtime | string)
      register: k8s_root_cacert_inode
      notify: Restart the haproxy service

  handlers:
    - name: Restart the haproxy service
      ansible.builtin.systemd_service:
        name: haproxy.service
        state: restarted
      become: true
