---
- name: Perform initial setup for k8s_worker
  hosts: k8s_workers
  tags: do_initial_k8s_worker_setup

  pre_tasks:
    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - k8s_node

  tasks:
    - name: Setup the Python virtual environment
      ansible.builtin.include_role:
        name: python_virtualenv
      vars:
        python_virtualenv_name: "{{ ansible_user_python_virtualenv_name }}"
        python_virtualenvs_path: "{{ ansible_user_python_virtualenvs_path }}"
        python_virtualenv_pkgs:
          - kubernetes

    - name: Add sourcing of the Python virtual environment
      ansible.builtin.import_role:
        name: cavcrosby.general.common
        tasks_from: managed_lineinfile
      vars:
        path: "{{ ansible_user_home }}/.bashrc"
        regexp: '^source "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/activate"'
        line: 'source "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/activate"'
        line_identifier: sourcing the {{ ansible_user_python_virtualenv_name }} Python virtual environment

    - name: Setup legacy iptables
      ansible.builtin.import_tasks: ./tasks/setup_legacy_iptables.yml

- name: Perform initial setup for k8s_worker (poseidon)
  hosts: k8s_workers:&poseidon
  tags: do_initial_poseidon_k8s_worker_setup
  vars_files:
    - ./vars/{{ k8s_software_versions_file }}

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Install containerd (debian-like)
      ansible.builtin.apt:
        name:
          - containerd={{ containerd_version }}
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Prevent containerd from being upgraded
      ansible.builtin.dpkg_selections:
        name: containerd
        selection: hold
      become: true
      when: ansible_os_family | lower == "debian"

  roles:
    - k8s_kubeadm

  tasks:
    - name: Add common handlers
      ansible.builtin.import_role:
        name: cavcrosby.general.common
        handlers_from: main

    - name: Configure firewall for the particular Calico deployment
      ansible.builtin.import_tasks: ./tasks/config_fw_calico.yml

- name: Configure k8s_worker to be a Kubernetes worker node
  hosts: k8s_workers
  tags: configure_host_as_k8s_worker_node
  vars_files:
    - "{{ network_configs_path }}"
    - ./vars/ansible_secrets.yml
  vars:
    ansible_python_interpreter: "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/python"

  pre_tasks:
    - name: Add common handlers
      ansible.builtin.import_role:
        name: cavcrosby.general.common
        handlers_from: main

  roles:
    - role: k8s_worker_node
      become: true
