---
- name: Install Helm charts (poseidon)
  hosts: k8s_first_controllers:&poseidon
  tags: install_poseidon_k8s_first_controller_helm_charts
  vars_files:
    - ./vars/{{ k8s_software_versions_file }}
    - ./vars/ansible_secrets.yml
  vars:
    ansible_python_interpreter: "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/python"

  tasks:
    - name: Install Ingress NGINX controller
      vars:
        ingress_nginx_namespace: ingress-nginx
        dockerhub_creds_secret_name: dockerhub-creds
      block:
        - name: Create the Ingress NGINX namespace
          kubernetes.core.k8s:
            api_version: v1
            kind: Namespace
            name: "{{ ingress_nginx_namespace }}"
            state: present
          become: true
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Apply the Ingress NGINX Kubernetes manifest to the cluster
          kubernetes.core.k8s:
            template: "{{ ingress_nginx_manifest_template }}"
            state: present
          become: true
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Add the Ingress NGINX Helm repo
          kubernetes.core.helm_repository:
            repo_name: ingress-nginx
            repo_url: https://kubernetes.github.io/ingress-nginx
          become: true

        - name: Deploy the Ingress NGINX Helm chart inside the ingress-nginx namespace
          kubernetes.core.helm:
            release_name: ingress-nginx
            chart_ref: ingress-nginx/ingress-nginx
            chart_version: "{{ ingress_nginx_chart_version }}"
            release_namespace: "{{ ingress_nginx_namespace }}"
            create_namespace: true
            release_state: present
            values: "{{ lookup('ansible.builtin.template', ingress_nginx_helm_values_file_template) | from_yaml }}"
          become: true
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
