---
- name: Install Helm charts (poseidon)
  hosts: k8s_first_controllers:&poseidon
  tags: install_poseidon_k8s_first_controller_helm_charts
  vars_files:
    - ./vars/{{ k8s_software_versions_file }}
    - ./vars/ansible_secrets.yml
  vars:
    ansible_python_interpreter: "{{ ansible_user_python_virtualenvs_path }}/{{ ansible_user_python_virtualenv_name }}/bin/python"

  tasks:
    - name: Install Ingress NGINX controller
      vars:
        ingress_nginx_namespace: ingress-nginx
        ingress_nginx_manifest_path: /tmp/{{ (ingress_nginx_manifest_template | basename | splitext)[:-1] | join('.') }}
        ingress_nginx_helm_values_file_path: /tmp/{{ (ingress_nginx_helm_values_file_template | basename | splitext)[:-1] | join('.') }}
        dockerhub_creds_secret_name: dockerhub-creds
      block:
        - name: Create the Ingress NGINX namespace
          kubernetes.core.k8s:
            api_version: v1
            kind: Namespace
            name: "{{ ingress_nginx_namespace }}"
            state: present
          become: true
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        # DISCUSS(cavcrosby): the kubernetes.core.k8s task has a template parameter that
        # can take a jinja template from the controller but vars such as 'ansible_managed'
        # for some reason are not known to this task and cause it to fail. I should
        # determine if said variable is worth keeping vs eliminating unnecessary tasks.
        - name: Create the Ingress NGINX Kubernetes resources manifest
          ansible.builtin.template:
            src: "{{ ingress_nginx_manifest_template }}"
            dest: "{{ ingress_nginx_manifest_path }}"
            mode: "600"

        - name: Apply the Ingress NGINX Kubernetes manifest to the cluster
          kubernetes.core.k8s:
            src: "{{ ingress_nginx_manifest_path }}"
            state: present
          become: true
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Create the Ingress NGINX Helm values file
          ansible.builtin.template:
            src: "{{ ingress_nginx_helm_values_file_template }}"
            dest: "{{ ingress_nginx_helm_values_file_path }}"
            mode: "600"

        - name: Add the Ingress NGINX Helm repo
          kubernetes.core.helm_repository:
            repo_name: ingress-nginx
            repo_url: https://kubernetes.github.io/ingress-nginx
          become: true

        - name: Deploy the Ingress NGINX Helm chart inside the ingress-nginx namespace
          kubernetes.core.helm:
            release_name: ingress-nginx
            chart_ref: ingress-nginx/ingress-nginx
            chart_version: "{{ ingress_nginx_chart_version }}"
            release_namespace: "{{ ingress_nginx_namespace }}"
            create_namespace: true
            release_state: present
            values_files:
              - "{{ ingress_nginx_helm_values_file_path }}"
          become: true
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
