---
- name: Install and configure haproxy
  hosts: load_balancers
  tags: install_haproxy_load_balancer
  vars_files:
    - "{{ network_configs_path }}"

  roles:
    - role: haproxy
      vars:
        haproxy_config_target_file: homelab-haproxy.cfg
