---
- name: Install and configure haproxy
  hosts: load_balancers
  tags: install_haproxy_load_balancer
  vars_files:
    - "{{ network_configs_path }}"

  pre_tasks:
    - name: Add local common handlers
      ansible.builtin.import_role:
        name: common
        handlers_from: main

  roles:
    - role: haproxy
      vars:
        haproxy_config_target_file: homelab-haproxy.cfg
