---
- name: Setup NFS server
  hosts: nfs_servers
  tags: setup_nfs_servers

  tasks:
    - name: Update apt's package index (debian-like)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Install the kernel space NFS server (debian-like)
      ansible.builtin.apt:
        name:
          - nfs-kernel-server
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the nfs.conf configuration file
      ansible.builtin.template:
        src: nfs.conf.j2
        dest: /etc/nfs.conf.d/homelab-nfs.conf
        mode: "644"
      become: true
      notify: Restart the nfs-server service

    - name: Create the NFS exports directory
      ansible.builtin.file:
        path: /srv/nfs
        state: directory
        mode: "755"
      become: true
      register: nfs_exports_dir

    - name: Mount the NFS exports' filesystems
      ansible.builtin.include_tasks: ./tasks/mount_nfs_filesystems.yml
      vars:
        nfs_export_dir_path:
          "{{ nfs_exports_dir.path }}/{{ outer_item.name |
          ansible.builtin.regex_replace('^lv(.+)', '\\1') }}"
      loop: "{{ lvm_disks_config.lvs }}"
      loop_control:
        loop_var: outer_item
      when: outer_item.vg_name == "vgnfs"

    - name: Create the exports(5) extra export tables directory
      ansible.builtin.file:
        path: /etc/exports.d
        state: directory
        mode: "755"
      become: true
      register: exports_extra_tables_dir

    - name: Create the homelab.exports configuration file
      ansible.builtin.template:
        src: nfs-homelab.exports.j2
        dest: "{{ exports_extra_tables_dir.path }}/homelab.exports"
        mode: "644"
      become: true
      notify: Reexport all the directories

  handlers:
    - name: Restart the nfs-server service
      ansible.builtin.systemd_service:
        name: nfs-server.service
        state: restarted
      become: true

    - name: Issue a systemd daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true
      become: true

    - name: Reexport all the directories
      ansible.builtin.command: exportfs -r
      changed_when: true
      become: true
