---
- name: Setup NFS client
  hosts: nfs_clients
  tags: setup_nfs_clients

  tasks:
    - name: Update apt's package index (debian-like)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Install the mount NFS helper program (debian-like)
      ansible.builtin.apt:
        name:
          - nfs-common
        state: present
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the NFS exports directories
      ansible.builtin.file:
        path: /nfs/{{ item.host }}
        state: directory
        mode: "755"
      become: true
      loop: "{{ nfs_exports_config }}"

    - name: Mount the NFS exports
      ansible.posix.mount:
        path: "{{ item.mountpoint }}"
        src: "{{ item.host }}:{{ item.device }}"
        fstype: nfs
        opts: "{{ item.options }}"
        state: mounted
      become: true
      loop: "{{ nfs_exports_config }}"
