---
- name: Perform packer customizations
  hosts:
    - k8s_workers
    - k8s_controllers
  tags: do_packer_customizations

  tasks:
    - name: Upgrade all packages (debian-like)
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the networking interfaces file (debian-like)
      ansible.builtin.template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        mode: "644"
      become: true
      when: ansible_os_family | lower == "debian"
