---
- name: Perform packer customizations
  hosts:
    - k8s_workers
    - k8s_controllers
  tags: do_packer_customizations

  tasks:
    - name: Upgrade all packages (debian-like)
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the networking interfaces file (debian-like)
      ansible.builtin.template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        mode: "644"
      become: true
      when: ansible_os_family | lower == "debian"

    - name: Create the resolver configuration file
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        mode: "644"
        content: |
          nameserver {{ preferred_nameserver }}
      become: true

    - name: Create the disable-make-resolv-conf script
      ansible.builtin.template:
        src: disable-make-resolv-conf.sh.j2
        dest: /etc/dhcp/dhclient-enter-hooks.d/disable-make-resolv-conf
        mode: "644"
      become: true

    - name: Truncate the etcetera local machine ID configuration file
      community.general.filesize:
        path: /etc/machine-id
        size: 0B
      become: true
      register: local_machine_id_file

    - name: Make the variables local machine ID configuration file a symbolic link
      ansible.builtin.file:
        state: link
        path: /var/lib/dbus/machine-id
        src: "{{ local_machine_id_file.path }}"
        force: true
      become: true
