---
- name: Add systemd.unified_cgroup_hierarchy=0 to grub boot command(s)
  hosts: ctrservers
  vars:
    default_grub_path: /etc/default/grub

  tasks:
    - name: Register the default grub configuration file inode
      ansible.builtin.stat:
        path: "{{ default_grub_path }}"
      become: yes
      register: default_grub_config_inode

    - name: Initial check if systemd.unified_cgroup_hierarchy=0 is added to GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.lineinfile:
        state: absent
        path: "{{ default_grub_path }}"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
      check_mode: true
      changed_when: false
      become: yes
      register: line_check

    - name: Add systemd.unified_cgroup_hierarchy=0 to GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.import_role:
        name: cavcrosby.general.common
        tasks_from: managed_lineinfile
      vars:
        path: "{{ default_grub_path }}"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} systemd.unified_cgroup_hierarchy=0"'
        line_identifier: append GRUB_CMDLINE_LINUX_DEFAULT with systemd.unified_cgroup_hierarchy=0
      become: yes
      when: default_grub_config_inode.stat.exists

    - name: Update grub.cfg
      ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
      become: yes
      when:
        - default_grub_config_inode.stat.exists
        - line_check.found == 0

    - name: Reboot ctrservers to have new boot parameter(s) take effect
      ansible.builtin.reboot:
      become: yes
      when: line_check.found == 0

- name: Provision VPS(s) setup on local VMs
  hosts: irc_clients

  pre_tasks:
    - name: Update apt's package index
      ansible.builtin.apt:
        update_cache: yes
      become: yes

  tasks:
    - name: Install cloud-init
      ansible.builtin.apt:
        name:
          - cloud-init
        state: present
      become: yes
