#!/bin/bash
#
# Approves CSRs that are pending from Kubernetes nodes' kubelets.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME
readonly ROOT_UID=0

if [ "$(id --user)" != "${ROOT_UID}" ]; then
    echo "${PROGNAME}: you must run this as root" >&2
    exit 1
fi

if [ -z "$(command -v jq)" ]; then
    echo "${PROGNAME}: jq cannot be found in the PATH!" >&2
    exit 1
fi

# empty JSON represents a CSR with a status of pending
for csr in $(kubectl get csr --output json \
    | jq --raw-output \
        '
        .items
        | map(select(.spec.signerName == "kubernetes.io/kubelet-serving" and .status == {}))
        | .[].metadata.name
        '); do
    kubectl certificate approve "${csr}"
done

exit 0
