---
# Everything under 'filename' will be recorded in the systemd network files template.
# Each section header is determined by the top level key in each hash.
#
# Example (yaml to resulting template):
#
#  Match:
#    Name: eth0
#  Network:
#    DHCP: ipv4
#
# ================
#
# [Match]
# Name=eth0

# [Network]
# DHCP=ipv4
#
systemd_networkd_files:
  - filename: "{{ ansible_default_ipv4.interface }}.link"
    Match:
      MACAddress: "{{ ansible_default_ipv4.macaddress }}"
    Link:
      NamePolicy: keep

  - filename: "{{ ansible_default_ipv4.interface }}.network"
    Match:
      Name: "{{ ansible_default_ipv4.interface }}"
    Network:
      DHCP: "ipv4"
